---
title: "Análise Exploratória"
author: "Matheus Leal, Matheus Maciel, Mariana Mendes, Leandro Lima, Victor Hugo"
date: "12 de novembro de 2018"
output: html_document
---

```{r message=FALSE,  warning=FALSE}
library(tidyverse)

avaliacoes <- read_csv("../data/3-avaliacao-humana/avaliacoes-20180610.csv")
reclamacoes <-  read_csv("../data/1-reclamacoes-selecionadas/reclamacoes-avaliadas.csv")
```


#####Adicionando colunas com o tamanho das reclamações, quantidade de exclamações e interrogações e a quantidade de letras em caixa alta.
```{r message=FALSE,  warning=FALSE}
reclamacoes <- reclamacoes %>% mutate(reclamacao.length = str_length(reclamacao))

reclamacoes$numero.de.capslock <- str_count(reclamacoes$reclamacao, "\\b[A-Z]{2,}\\b")

reclamacoes$numero.pontuacao <- str_count(reclamacoes$reclamacao, "\\!") + str_count(reclamacoes$reclamacao, "\\?")
```


**Tamanho das reclamações**
```{r message=FALSE,  warning=FALSE}
reclamacoes %>% 
  filter(complete.cases(.)) %>% 
  ggplot(aes(fill = orgao, x = reclamacao.length), na.rm = TRUE) + 
  geom_histogram(binwidth = 50, na.rm = TRUE) + 
  facet_grid(orgao ~ .)
```


**Quantidade de carácteres em caixa alta**
```{r message=FALSE,  warning=FALSE}
reclamacoes %>% 
  ggplot(aes(x = numero.de.capslock), na.rm = TRUE) + 
  geom_histogram()
```

**Quantidade de carácteres em caixa alta por orgão**
```{r message=FALSE,  warning=FALSE}
reclamacoes %>% 
  ggplot(aes(fill = orgao, x = numero.de.capslock), na.rm = TRUE) + 
  geom_histogram() + facet_grid(orgao ~ .)
```

**Quantidade de avaliadores de uma mesma reclamação**
```{r message=FALSE,  warning=FALSE}
avaliadores <- table(avaliacoes$`ID da reclamação`)
contador <-integer(60)
for (i in 1:length(avaliacoes$`Grau de insatisfação`)){
  contador[avaliacoes$`ID da reclamação`[i]] <- contador[avaliacoes$`ID da reclamação`[i]] + 1
}
hist(contador)
```

**Quantidade de avaliadores de uma mesma reclamação**
```{r message=FALSE,  warning=FALSE}
avaliadores <- table(avaliacoes$`ID da reclamação`)
contadorMax <- 1
contadorMin <- 1
questoesMaximas <- 1:100
questoesMinimas <- 1:100
for (i in 1:length(avaliacoes$`Grau de insatisfação`)){
  if(avaliacoes$`Grau de insatisfação`[i] == 5){
    questoesMaximas[contadorMax] <- avaliacoes$`ID da reclamação`[i]
    contadorMax <- contadorMax + 1
  }
}

for (i in 1:length(avaliacoes$`Grau de insatisfação`)){
  if(avaliacoes$`Grau de insatisfação`[i] == 5){
    questoesMinimas[contadorMin] <- avaliacoes$`ID da reclamação`[i]
    contadorMin <- contadorMin + 1
  }
}

questoesMaximas

questoesIguais <- integer(60)
contador <- 1
for (i in 1:length(questoesMaximas)){
  for (j in 1:length(questoesMinimas)){
    if (questoesMaximas[i] == questoesMinimas[j]){
      questoesIguais[contador] <- questoesMaximas[i]
      contador <- contador + 1
    }
  }
}

questoesMinimas
questoesMaximas
questoesIguais <- sort(unique(questoesIguais))


```
